py_binary(
    name = "c_stuff_sack",
    srcs = ["c_stuff_sack.py"],
    deps = [
        ":stuff_sack",
    ],
    visibility = ["//visibility:public"],
)

py_library(
    name = "stuff_sack",
    srcs = ["stuff_sack.py"],
)
